services:
  coverly-api:
    container_name: coverly-api
    image: ghcr.io/flowergardn/coverly/api:latest
    env_file:
      - ./.env
    restart: always
    environment:
      PORT: "3000"
    ports:
      - 3001:3000
